### ISSUE TITLE
`runner.os` in the cache key

### ISSUE THREAD

**Issue by gagbo** [doomemacs/ci#1]
### What would you like to know?

Do you really need to add `runner.os` in the cache key if you are simply putting clones of git repositories in the cache values ? If the straight recipes don't change for each OS, I don't see a reason to make 3 different caches of `straight/repos` for the same profile on 3 os.

Then again, I don't know what information the hash of the profile contains, so feel free to close that

**Comment by hlissner** [comment]
You're right: some modules and packages may be installed conditionally, based on OS (such as `:os macos`), so the package list isn't stable between them, but `doom profile hash` generates [a hash](https://github.com/doomemacs/ci/blob/main/action.yml#L61) of the entire (OS-sensitive) package list, so `runner.os` isn't really necessary anymore, so I've removed it in 8944720. 

Thanks for bringing it to my attention!
